
# ======================
# DATABASE CONFIG
# ======================
spring.datasource.url=jdbc:mysql://localhost:3306/restaurants_db
spring.datasource.username=Sam_spark
spring.datasource.password=java

# ======================
# JPA / HIBERNATE
# ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true





info.app.name=restaurant-service
info.app.description=This is restaurant service dev env
info.app.version=1.V Development
